name: Test and Publish

on:
  push:
    branches: [ master ]

jobs:
  clippy_check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run Clippy
      run: cargo clippy --all-targets --all-features -- -Dwarnings

  test:
    needs: clippy_check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12']
    name: Python ${{ matrix.python-version }} testing
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install tox tox-gh-actions
    - name: Test with tox
      run: |
        python -m tox

  version_job:
    needs: test
    outputs:
      version: ${{ steps.generate_version.outputs.version }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Generate version
      id: generate_version
      run: |
        echo "version=$(python scripts/generate_version.py)" >> $GITHUB_OUTPUT

  linux:
    needs: version_job
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - uses: dtolnay/rust-toolchain@stable
    - name: Set version
      run: |
        cargo install set-cargo-version
        set-cargo-version Cargo.toml ${{needs.version_job.outputs.version}}
    - uses: PyO3/maturin-action@v1
      with:
        maturin-version: latest
        manylinux: auto
        command: build
        args: --release -o dist -i python3.10 -i python3.11 -i python3.12
    - name: Upload wheels
      uses: actions/upload-artifact@v3
      with:
        name: wheels
        path: dist

  windows:
    needs: version_job
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable
    - name: Set version
      run: |
        cargo install set-cargo-version
        set-cargo-version Cargo.toml ${{needs.version_job.outputs.version}}
    - uses: PyO3/maturin-action@v1
      with:
        maturin-version: latest
        command: build
        args: --release -o dist
    - name: Upload wheels
      uses: actions/upload-artifact@v3
      with:
        name: wheels
        path: dist

  macos:
    needs: version_job
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable
    - name: Set version
      run: |
        cargo install set-cargo-version
        set-cargo-version Cargo.toml ${{needs.version_job.outputs.version}}
    - uses: PyO3/maturin-action@v1
      with:
        maturin-version: latest
        command: build
        target: universal2-apple-darwin
        args: --release -o dist
    - name: Upload wheels
      uses: actions/upload-artifact@v3
      with:
        name: wheels
        path: dist

  publish:
    needs: [ macos, windows, linux ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: wheels
      - name: Publish to PyPI
        uses: messense/maturin-action@v1
        env:
          MATURIN_PYPI_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
        with:
          command: upload
          args: --skip-existing *
